### ISSUE TITLE
Діма Сторожук - лід модуля panels

### ISSUE THREAD

**Issue by podarok** [drupal-ukraine/maintainer#24]
@dstorozhuk 

- отримати доступ на запис до модуля
- написати roadmap

**Comment by dstorozhuk** [comment]
👍 Быстро ) 
Я об этом только вчера с Толей подумал.
Буду держать в курсе тут.

**Comment by dstorozhuk** [comment]
@podarok Есть ли Trello для таких задач и вообще пользуете ли вы Trello для opensorce проектов?

**Comment by podarok** [comment]
@dstorozhuk https://github.com/orgs/drupal-ukraine/projects/1 пробуємо цього року використовувати GitHub project

**Comment by podarok** [comment]
план всього спринта від @podarok

Мета - make panels great again
Ресурси - люди, які трошки розуміють Drupal 8, render pipeline, services, schema config.
Діма: глянути всі issue, реалізувати до панелі в межах контексту, доступ до кожного блоку, блоки які надаються page manager display plugin, panels display plugin, panels cloning (clone, share patch with Dima @podarok )
Блокери - незрозуміло, перечитати реліз Drupal 8.3, layout_plugin in core. @dstorozhuk Зібрати META issues по всім модулям
Менеджмент інформації ? - на кафе розповісти про панелі, для чого вони потрібні, чому параграфи не заміняють панелі. Зацікавити людей. @anpolimus 16 березня кафе? . Зібрати список фіч Drupal 7 panels, яких фіч немає зараз в панелях, яких фіч немає в параграфах зовсім. Було б непогано доповідь записати на відео.
Менеджмент проекту ? github? drupal.org? **bitbucket**!
Час ? Почали зараз.
Завершення проекту ? На кодспринті, тиждень після. Все, що є робимо патчі, якщо буда запис в репо, комітимо в модуль. Якщо не буде - @dstorozhuk буде пінгувати патчі на коміт.
Звіт ? @dstorozhuk знайти PM, який буде присутній на спринті і можливо впродовж всього цього часі і напише зіт.


Як буде відбуватись процес на самому спринті ?
Ставим зону, прапорець Панелі, Діма + команда. просетапити kick-off перед спринтом і розбити ролі. Гугл форму на спринт. Створити форму! За тиждень-два провести зустріч. На спринті kick-off перед початком.

Хто може тебе замінити, якщо форс мажор ? Питання відкрите. Знайти людину.

Наступні кроки ?
В рамках drupal-ukraine:
1. Перевірити актуальність панелей в 8.3 @dstorozhuk 
2. Створити проект панелей @podarok
3. Закинути заявку на maintainer проекту на drupal.org @andypost ???
4. Нагенерувати задач по цій зустрічі @podarok
5. Шукати ресурси. ? @podarok Інформування в соцмережах.
6. Додати Діму в Слак організаторів. #code_sprint_17
7. Пофіксити maintainer @podarok 
8. Знайти менеджера проекту @dstorozhuk

**Comment by dstorozhuk** [comment]
TODO: Собрать meta issue по panels, page manager, layout plugin, ctools

**Comment by dstorozhuk** [comment]
TODO: сделать список ссылок с инфой рендерингу в drupal 8

**Comment by podarok** [comment]
https://www.facebook.com/groups/104220905217/permalink/10154809483780218/
